// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTm0flwVOpPEbZHFXbJL8I_8q9y1C3s30',
    appId: '1:33136199672:android:dd54c64807fdbee1a3b80d',
    messagingSenderId: '33136199672',
    projectId: 'login-page-b1bde',
    storageBucket: 'login-page-b1bde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHCD-FueG3ektVTAr_2e2yQaJ4J0UxKqY',
    appId: '1:33136199672:ios:bf68f6f3a4e83ce8a3b80d',
    messagingSenderId: '33136199672',
    projectId: 'login-page-b1bde',
    storageBucket: 'login-page-b1bde.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );
}
