// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArfYqlnAO9Uquu3Jji0Kbhk3pDB4GLAEw',
    appId: '1:33136199672:web:f03bf76874f985c9a3b80d',
    messagingSenderId: '33136199672',
    projectId: 'login-page-b1bde',
    authDomain: 'login-page-b1bde.firebaseapp.com',
    storageBucket: 'login-page-b1bde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTm0flwVOpPEbZHFXbJL8I_8q9y1C3s30',
    appId: '1:33136199672:android:dd54c64807fdbee1a3b80d',
    messagingSenderId: '33136199672',
    projectId: 'login-page-b1bde',
    storageBucket: 'login-page-b1bde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHCD-FueG3ektVTAr_2e2yQaJ4J0UxKqY',
    appId: '1:33136199672:ios:bf68f6f3a4e83ce8a3b80d',
    messagingSenderId: '33136199672',
    projectId: 'login-page-b1bde',
    storageBucket: 'login-page-b1bde.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHCD-FueG3ektVTAr_2e2yQaJ4J0UxKqY',
    appId: '1:33136199672:ios:bf68f6f3a4e83ce8a3b80d',
    messagingSenderId: '33136199672',
    projectId: 'login-page-b1bde',
    storageBucket: 'login-page-b1bde.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArfYqlnAO9Uquu3Jji0Kbhk3pDB4GLAEw',
    appId: '1:33136199672:web:f5c36c01bcdeffcca3b80d',
    messagingSenderId: '33136199672',
    projectId: 'login-page-b1bde',
    authDomain: 'login-page-b1bde.firebaseapp.com',
    storageBucket: 'login-page-b1bde.appspot.com',
  );
}
